name: rocket
description: File sharing is rocket science. A demo app that allows file sharing on the same network.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_ip: ^0.4.0
  file_picker: ^1.10.0
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  socket_io: ^0.9.4
  connectivity: ^0.4.8+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - client/
    - assets/

